In [2]:

import numpy as np


In [2]:
#시드 설정하기

np.random.seed(0)

In [3]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [4]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [5]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [7]:
np.random.seed(0)

In [8]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [9]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [10]:
#데이터의 순서 바꾸기

x = np.arange(10)

x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.random.shuffle(x)

x

array([5, 1, 8, 2, 6, 7, 0, 3, 4, 9])

In [12]:
#데이터 샘플링

np.random.choice(5, 5, replace = False)

#replace: True이면 한번 선택한 데이터를 다시 선택 가능

array([0, 4, 2, 1, 3])

In [15]:
np.random.choice(5, 3, replace=False)

array([4, 2, 3])

In [16]:
np.random.choice(5, 10) #반복해서 10개 선택

array([0, 2, 4, 3, 3, 2, 4, 2, 0, 0])

In [17]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])  # 선택 확률을 다르게 해서 10개 선택

array([2, 2, 2, 2, 3, 3, 3, 3, 0, 3])

In [ ]:
#난수 생성

#rand: 0부터 1사이의 균일 분포

#randn: 표준 정규 분포

#randint: 균일 분포의 정수 난수

In [18]:
np.random.rand(10)

array([0.65314004, 0.17090959, 0.35815217, 0.75068614, 0.60783067,
       0.32504723, 0.03842543, 0.63427406, 0.95894927, 0.65279032])

In [22]:
np.random.rand(3, 5)

array([[0.01357164, 0.6228461 , 0.67365963, 0.971945  , 0.87819347],
       [0.50962438, 0.05571469, 0.45115921, 0.01998767, 0.44171092],
       [0.97958673, 0.35944446, 0.48089353, 0.68866118, 0.88047589]])

In [21]:
np.random.randn(10)

array([-1.73495876,  1.65835111,  2.29977152, -0.47113526,  1.26271548,
       -1.17051545,  1.0657892 , -0.69993739,  0.14407911,  0.3985421 ])

In [23]:
np.random.randn(3, 5)

array([[ 1.07612104,  0.19214083,  0.85292596,  0.01835718,  0.42830357],
       [ 0.99627783, -0.49114966,  0.71267817,  1.11334035, -2.15367459],
       [-0.41611148, -1.07089699,  0.22113881, -1.12305712, -1.05075796]])

In [24]:
np.random.randint(10, size=10)

array([0, 8, 8, 3, 8, 2, 8, 4, 3, 0])

In [25]:
np.random.randint(10, 20, size=10)

array([14, 13, 16, 19, 18, 10, 18, 15, 19, 10])

In [26]:
np.random.randint(10, 20, size=(3, 5))

array([[19, 16, 15, 13, 11],
       [18, 10, 14, 19, 16],
       [15, 17, 18, 18, 19]])

numpy.random.choice(a, size=None, replace=True, p=None)


a : 배열이면 원래의 데이터, 정수이면 arange(a) 명령으로 데이터 생성

size : 정수. 샘플 숫자

replace : 불리언. True이면 한번 선택한 데이터를 다시 선택 가능

p : 배열. 각 데이터가 선택될 수 있는 확률


In [3]:
#연습문제 3.5.1

np.random.choice(2, 10, p=[0.5, 0.5])

array([0, 1, 1, 1, 0, 0, 0, 0, 0, 0])

In [5]:
dice = np.random.randint(1, 7, 100)

dice.mean()

3.49

#정수 데이터 카운팅

#unique: 데이터에서 중복된 값을 제거하고 중복되지 않는 값의 리스트를 출력

#return_counts 인수를 True로 설정하면 각 값을 가진 데이터 갯수도 출력

In [6]:
np.unique([11, 11, 2, 2, 34, 34])

array([ 2, 11, 34])

In [7]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts = True)

In [8]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [9]:
count

array([2, 2, 1], dtype=int64)

In [10]:
np.bincount([1, 1, 2, 2, 2, 3], minlength = 6)

array([0, 2, 3, 1, 0, 0], dtype=int64)