In [2]:
import numpy as np

In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

                                              0.0/15.5 MB ? eta -:--:--
     --                                       0.9/15.5 MB 19.4 MB/s eta 0:00:01
     --------                                 3.2/15.5 MB 40.6 MB/s eta 0:00:01
     ---------------                          5.9/15.5 MB 47.2 MB/s eta 0:00:01
     ---------------------                    8.3/15.5 MB 48.3 MB/s eta 0:00:01
     -------------------------               10.4/15.5 MB 50.4 MB/s eta 0:00:01
     --------------------------              10.5/15.5 MB 50.4 MB/s eta 0:00:01
     -----------------------------           11.8/15.5 MB 40.9 MB/s eta 0:00:01
     -----------------------------------     14.2/15.5 MB 38.5 MB/s eta 0:00:01
     --------------------------------------  15.5/15.5 MB 38.6 MB/s eta 0:00:01
     --------------------------------------  15.5/15.5 MB 38.6 M


[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [4]:
a = np.array([1,2, '유미'])
print(a)
print(type(a))

['1' '2' '유미']
<class 'numpy.ndarray'>


In [5]:
def sum(a, b):
    return a+b

In [6]:
sum(1,2)

3

In [7]:
basic_list = [1, 2, 3, 4, 5, 6]

new_basic_list = []
for i in basic_list:
    new_basic_list.append(i * 10)

print(new_basic_list)

[10, 20, 30, 40, 50, 60]


In [8]:
#벡터화 연산

np_array = np.array(basic_list)


np_array + 10 

array([11, 12, 13, 14, 15, 16])

In [9]:
basic_list + 1

TypeError: can only concatenate list (not "int") to list

In [10]:
a = np.array([100, 100, 130])
b = np.array([40, 45, 48])
c = np.array(["유미","태근","돼지"])

In [11]:
(a ==130) & (b >= 45)

array([False, False,  True])

In [12]:
#2차원 배열 만들기

array_2dim = np.array([[100, 100, 130], [40, 45, 48]])

In [13]:
array_2dim

array([[100, 100, 130],
       [ 40,  45,  48]])

In [4]:
c = np.array([[0, 1, 2], [4, 5, 6]])

In [5]:
c

array([[0, 1, 2],
       [4, 5, 6]])

In [6]:
len(c)

2

In [7]:
len(c[0])

3

In [8]:
#연습문제1

matrix = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])

In [9]:
print(matrix)

[[10 20 30 40]
 [50 60 70 80]]


In [11]:
#3차원 배열 만들기

d = np.array([[[10, 20, 30, 40], [50, 60, 70, 80]], [[1, 2, 3, 4], [5, 6, 7, 8]]])

In [12]:
print(d)

[[[10 20 30 40]
  [50 60 70 80]]

 [[ 1  2  3  4]
  [ 5  6  7  8]]]


In [13]:
#배열의 차원과 크기 알아내기

d.ndim

3

In [14]:
d.shape

(2, 2, 4)

In [16]:
matrix.ndim

2

In [17]:
matrix

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [24]:
#matrix[행, 열]

matrix[:,1:]

array([[20, 30, 40],
       [60, 70, 80]])

In [25]:
#배열 슬라이싱
matrix[1, 1:3]

array([60, 70])

In [26]:
#연습문제 2

m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

In [27]:
#1
m[1, 2]

7

In [28]:
#2
m[2, 4]

14

In [30]:
#3
m[1, 1:3]

array([6, 7])

In [31]:
#4
m[1:3, 2]

array([ 7, 12])

In [32]:
#5
m[0:2, 3:5]

array([[3, 4],
       [8, 9]])

In [33]:
# 배열 인덱싱

a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True, False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [35]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [37]:
#연습문제 3

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [38]:
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [39]:
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [45]:
x[(x % 3 ==0) & (x % 4 == 1)]

array([9])