In [1]:
import numpy as np

In [2]:
#벡터화 연산

x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [5]:
%%time 
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

CPU times: total: 0 ns
Wall time: 6.02 ms


In [6]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [7]:
%%time 
z = x + y

CPU times: total: 0 ns
Wall time: 2 ms


In [8]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [9]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

In [10]:
a == b

array([False,  True, False,  True])

In [11]:
a >= b

array([False,  True,  True,  True])

In [12]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [13]:
# 배열의 각 원소들을 일일히 비교하는 것이 아니라 모든 원소가 다 같은지 알고 싶다면 all 명령 사용

np.all(a == b)

False

In [14]:
np.all(a == c)

True

In [6]:
# 스칼라와 벡터/행렬의 곱셈

x = np.arange(10)

x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [18]:
x = np.arange(12).reshape(3, 4)

x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

In [7]:
# 브로드캐스팅 : 벡터끼리 덧셈 혹은 뺄셈을 하려면 두 벡터의 크기가 같아야 함


x = np.arange(5)

x

array([0, 1, 2, 3, 4])

In [21]:
y = np.ones_like(x)

y

array([1, 1, 1, 1, 1])

In [22]:
x + y

array([1, 2, 3, 4, 5])

In [23]:
x + 1

array([1, 2, 3, 4, 5])

In [10]:
x = np.vstack([range(7)[i:i + 3] for i in range(5)])

x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [11]:
#np.newaxis: np행렬의 차원을 확장하는 함수

y = np.arange(5)[:, np.newaxis]

y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [12]:
x + y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [14]:
y = np.arange(3)

y

array([0, 1, 2])

In [15]:
x + y

array([[0, 2, 4],
       [1, 3, 5],
       [2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

In [16]:
# 차원 축소 연산

x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [17]:
np.sum(x)

10

In [18]:
x.sum()

10

In [19]:
x = np.array([1, 3, 2])

x

array([1, 3, 2])

In [20]:
x.min()

1

In [21]:
x.max()

3

In [22]:
x.argmin()

0

In [23]:
x.argmax()


1

In [24]:
x = np.array([1, 2, 3, 1])

In [27]:
x.mean()

1.75

In [2]:
a = np.zeros((100, 100), dtype=np.int)
a

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [31]:
# 정렬

a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [32]:
np.sort(a)

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [33]:
#axis=0이면 각각의 행을 따로따로 정렬하고 axis=1이면 각각의 열을 따로따로 정렬

np.sort(a, axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [34]:
#argsort: 순서
a = np.array([42, 38, 12, 25])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [4]:
#연습문제 3.3.2

x = np.array([[  1,    2,    3,    4],
       [ 46,   99,  100,   71],
       [ 81,   59,   90,  100]])



In [12]:

order = x.argsort(axis=1)[1]

x[:, order]


array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])