# 파이썬 대표 자료구조

**리스트(List)** 
- 장점 : 컬랙션에 다양한 타입의 요소를 담을 수 있음. 
- 단점 : 속도가 느리다.

대안이 필요했다.

**배열(Array)**
- 장점 : 속도가 빠르다.
- 단점 : 컬랙션에 단일 요소의 타입만 담을 수 있음.

파이썬에서는 배열 컬랙션이 존재하지 않는다.
하지만, 외부에서 누군가가 그것을 만들어놓음. => Numpy

In [2]:
#넘파이 라이브러리 설치

import numpy as np

In [9]:
# 파이썬의 리스트 컬랙션

python_list = [1,2,3,4,5]
print("파이썬 리스트" , python_list)
print("파이썬 리스트 타입" , type(python_list))

print()

numpy_array = np.array(python_list)
print("넘파이 배열" , numpy_array)
print("넘파이 배열 타입" , type(numpy_array))

파이썬 리스트 [1, 2, 3, 4, 5]
파이썬 리스트 타입 <class 'list'>

넘파이 배열 [1 2 3 4 5]
넘파이 배열 타입 <class 'numpy.ndarray'>


넘파이의 배열 타입은 우리가 원하는 벡터라이즈 연산을 지원한다.
따라서, 아래와 같이 우리가 원하는 표현대로 나오는 것은 넘파이의 연산이다.

In [12]:
print(python_list * 2)
print(numpy_array * 2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


In [13]:
numpy_array > 3

array([False, False, False,  True,  True])

In [14]:
name_array = np.array(["유미", "태근", "철용", "현준"])
height_array = np.array([163, 180, 170, 175])
weight_array = np.array([50, 70, 60, 65])

In [20]:
hegiht_meter_array = (height_array /100) ** 2
bmi_array = weight_array / hegiht_meter_array
bmi_array

array([18.81892431, 21.60493827, 20.76124567, 21.2244898 ])

In [24]:
def calc_bmi(height, weight):
    bmi = weight / (((height + 10) / 100) ** 2)
    return bmi

In [25]:
calc_bmi(height_array, weight_array)

array([16.70620468, 19.39058172, 18.51851852, 18.99196494])

In [23]:
result = []
for i in range(len(weight_array)):
    _bmi = weight_array[i] / ((height_array[i]/100) ** 2)
    result.append(_bmi)

resul

[18.818924310286427,
 21.604938271604937,
 20.761245674740486,
 21.224489795918366]

만약에 배열의 크기가 일치하지 않을때 벡터라이즈 연산이 어떻게 될까 ?

In [31]:
try:
    a = np.array([1,2,3])
    b = np.array([1,1,1,1])
    a + b
except ValueError as e:
    print( e , "에러가 발생하였습니다.")
    print("요소의 갯수가 맞지 않으면 벡터라이즈 연산이 불가능합니다.")


operands could not be broadcast together with shapes (3,) (4,)  에러가 발생하였습니다.
요소의 갯수가 맞지 않으면 벡터라이즈 연산이 불가능합니다.


In [34]:
name_array[height_array.argmin()]

'유미'

In [45]:
np.sort(height_array)

array([163, 170, 175, 180])

In [39]:
height_array

array([163, 170, 175, 180])

In [5]:
#넘파이의 자료형

x = np.array([1, 2, 3])

x.dtype

dtype('int32')

In [6]:
x = np.array([1.0, 2.0, 3.0])

x.dtype

dtype('float64')

In [7]:
x = np.array([1, 2, 3], dtype = 'f')
x.dtype

dtype('float32')

In [8]:
x[0] + x[1]

3.0

In [9]:
#Inf와 NaN

np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_20128\2068585620.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_20128\2068585620.py:1: RuntimeWarning: invalid value encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])

In [11]:
#배열 생성

a = np.zeros(5)

a

array([0., 0., 0., 0., 0.])

In [12]:
b = np.zeros((2, 3))

b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
d = np.zeros(5, dtype="U4")
d

array(['', '', '', '', ''], dtype='<U4')

In [15]:
d[0] = "abc"
d[1] = "abcd"
d[2] = "ABCDE"
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [16]:
e = np.ones((2, 3, 4), dtype = 'i8')

e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(3, 21, 2)

#시작, 끝(포함X), 단계

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [21]:
#전치 연산 : 행과 열을 바꾸는 작업

A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [4]:
#배열의 크기 변형

a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
b = a.reshape(3, 4)

b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
a.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
a.reshape(2, 2, -1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [8]:
a.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [9]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
x = np.arange(5)

x

array([0, 1, 2, 3, 4])

In [13]:
x.reshape(5, 1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [14]:
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [15]:
#배열 연결

a1 = np.ones((2, 3))

a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
a2 = np.zeros((2, 2))

a2

array([[0., 0.],
       [0., 0.]])

In [18]:
np.hstack([a1, a2])

#행의 수가 같은 두 개 이상의 배열을 옆으로 연결

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [19]:
b1 = np.ones((2, 3))

b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
b2 = np.zeros((3, 3))

b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.vstack([b1, b2])

#vstack : 열의 수가 같은 두 개 이상의 배열을 위아래로 연결

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
c1 = np.ones((3, 4))

c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
c2 = np.zeros((3, 4))


c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.dstack([c1, c2])

#dstack : 행이나 열이 아닌 깊이 방향으로 배열을 합침

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [9]:
np.dstack([c1, c2]).shape

(3, 4, 2)

In [15]:
c = np.stack([c1, c2], axis = 1)

c

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [16]:
c.shape

(3, 2, 4)

In [17]:
np.r_[np.array([1, 2, 3]), np.array([4, 5, 6])]

#r_ : 좌우 연결

array([1, 2, 3, 4, 5, 6])

In [18]:
np.c_[np.array([1, 2, 3]), np.array([4, 5, 6])]

#c_ : 배열의 차원 증가시킨 후 좌우 연결

array([[1, 4],
       [2, 5],
       [3, 6]])

In [19]:
a = np.array([[0, 1, 2], [3, 4, 5]])
np.tile(a, 2)

#tile: 동일한 배열을 반복하여 연결

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [20]:
#2차원 그리드 포인트 생성

x = np.arange(3)

x

array([0, 1, 2])

In [22]:
y = np.arange(5)

y

array([0, 1, 2, 3, 4])

In [23]:
X, Y = np.meshgrid(x, y)

In [24]:
X

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [25]:
Y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [27]:
[list(zip(x, y)) for x, y in zip(X, Y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

In [29]:
#연습문제 3.2.1

array([[   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [  10.,   20.,   30.,   40.,   50.],
       [  60.,   70.,   80.,   90.,  100.],
       [ 110.,  120.,  130.,  140.,  150.],
       [   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [  10.,   20.,   30.,   40.,   50.],
       [  60.,   70.,   80.,   90.,  100.],
       [ 110.,  120.,  130.,  140.,  150.]])

In [39]:
a0 = np.zeros([3, 3])
a1 = np.ones([3, 2])

a = np. hstack([a0, a1])

a

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [41]:
x10 = np.arange(10, 160, 10)

x10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150])

In [43]:
x = x10.reshape(3, 5)

x

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150]])

In [49]:
np.tile(np.vstack([a, x]), (2, 1))

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])